[package]
name = "sqlite-readers-writers"
version = "0.1.0"
authors = ["Mahmoud Al-Qudsi <mqudsi@neosmart.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random-fast-rng = "0.1.1"
rusqlite = "0.21.0"
